version: '3.9'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "3000:8080"
    tty: true
    depends_on:
      - "db"
    environment:
      TZ: Asia/Tokyo


  db:
    container_name: db
    image: mysql:8.0.15
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    command: mysqld
    cap_add:
      - SYS_NICE

    # depends_on:
    #   - "app"