version: '3.9'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/dev_app/Dockerfile
    ports:
      - "3000:8080"
    tty: true
    depends_on:
      - "db"
    environment:
      TZ: Asia/Tokyo
